[package]
name = "keywords"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "keyword_map_benchmark"
harness = false
